import {
  Link,
  Activity,
  Brain,
  Utensils,
  AlertCircle,
} from "lucide-react";

export const SYMPTOM_CATEGORIES = [
  {
    title: "Pain & Inflammation",
    icon: Link,
    color: "text-indigo-500",
    symptoms: [
    "Anti-inflammatory",
    "Mild–moderate pain",
    "Inflammation",
    "Body stiffness",
    "Arthritis",
    "Muscle stiffness",
    "Chronic pain",
    "Cancer pain",
    "Autoimmune pain",
    "Severe inflammation",
    "Arthritis pain",
    "Back/neck pain",
    "Menstrual cramps",
    "Spasm relief",
    "Fibromyalgia",
    "Motor neuron disease",
    "Multiple sclerosis"
    ],
  },
  {
    title: "Mental Health & Sleep",
    icon: Activity,
    color: "text-purple-500",
    symptoms: [
      "Anxiety",
    "Depression",
    "OCD",
    "Mood balancing",
    "Stress regulation",
    "Daily stress",
    "Fatigue",
    "Low energy",
    "Focus & productivity",
    "Mood stabilize",
    "Insomnia",
    "Sleep disturbances",
    "Midnight awakenings",
    "Stress-induced insomnia",
    "Improved circadian rhythm",
    "Severe insomnia",
    "Anxiety relief",
    "Emotional burnout",
    "Unwind",
    "Relaxation",
    "Emotional stability",
    "Calming high",
    "Better sleep",
    "Sleep improvement"
    ],
  },
  {
    title: "Neurological Conditions",
    icon: Brain,
    color: "text-blue-500",
    symptoms: [
      "Pediatric ASD",
    "Adult Epilepsy",
    "Epilepsy",
    "ADHD",
    "Alzheimer’s",
    "Cognitive support",
    "Behavioural stability",
    "Neuroprotective",
    "Multiple sclerosis",
    "Motor neuron disease"
    ],
  },
  {
    title: "Digestive Issues",
    icon: Utensils,
    color: "text-orange-500",
    symptoms: [
    "Nausea",
    "Vomiting",
    "Nausea control",
    "Appetite boost",
    "Appetite improvement"
    ],
  },
  {
    title: "Other Medical Conditions",
    icon: AlertCircle,
    color: "text-green-500",
    symptoms: [
    "Cancer care",
    "Cancer pain",
    "Autoimmune pain",
    "De-addiction",
    "De-alcoholism",
    "Craving reduction",
    "Alcohol withdrawal",
    "Craving control",
    "Respiratory issues",
    "Lung cleansing",
    "Smoker’s lung support",
    "Post-infection recovery",
    "Airway inflammation reduction",
    "Cough & wheezing relief",
    "Ayurvedic Vata balancing"
    ],
  },
];